# @see https://github.com/adrienverge/yamllint/blob/HEAD/yamllint/conf/default.yaml
---
extends: default

rules:
  line-length:
    max: 120
  quoted-strings:
    quote-type: single
    required: only-when-needed
  truthy:
    ignore: |
      /.github/workflows/*.yml
